### PR TITLE
Support `vector` HEAD

### PR DESCRIPTION
**Pull request by parsonsmatt**
This PR adds support for `vector` HEAD, necessary for GHC 9.4.

Lots of failures due to CPP. The bounds checking stuff with CPP was removed in favor of CallStacks.

Fails:

```

src/Data/Vector/Algorithms/Optimal.hs:80:99: error:
    • Couldn't match type: [Char]
                     with: Int -> Int -> m1 () -> a4
      Expected: Int -> Int -> m1 () -> a4
        Actual: String
    • In the fourth argument of ‘Ck.checkIndex’, namely
        ‘"sort3ByIndex"’
      In the first argument of ‘($)’, namely
        ‘((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 80)
            Ck.Unsafe)
           "sort3ByIndex" k (length a)’
      In the second argument of ‘($)’, namely
        ‘((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 80)
            Ck.Unsafe)
           "sort3ByIndex" k (length a)
           $ do a0 <- unsafeRead a i
                a1 <- unsafeRead a j
                a2 <- unsafeRead a k
                case cmp a0 a1 of
                  GT
                    -> case cmp a0 a2 of
                         GT -> ...
                         _ -> ...
                  _ -> case cmp a1 a2 of
                         GT -> ...
                         _ -> ...’
   |
80 |                          $ UNSAFE_CHECK(checkIndex) "sort3ByIndex" k (length a) $ do
   |                                                                                                   ^^^^^^^^^^^^^^

src/Data/Vector/Algorithms/Optimal.hs:117:46: error:
    • Couldn't match type ‘[Char]’ with ‘Ck.Checks’
      Expected: Ck.Checks
        Actual: String
    • In the first argument of ‘Ck.checkIndex’, namely
        ‘"src/Data/Vector/Algorithms/Optimal.hs"’
      In the first argument of ‘($)’, namely
        ‘((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 117)
            Ck.Unsafe)
           "sort4ByIndex" i (length a)’
      In the expression:
        ((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 117)
           Ck.Unsafe)
          "sort4ByIndex" i (length a)
          $ ((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 118)
               Ck.Unsafe)
              "sort4ByIndex" j (length a)
              $ ((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 119)
                   Ck.Unsafe)
                  "sort4ByIndex" k (length a)
                  $ ((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 120)
                       Ck.Unsafe)
                      "sort4ByIndex" l (length a)
                      $ do a0 <- unsafeRead a i
                           a1 <- unsafeRead a j
                           a2 <- unsafeRead a k
                           a3 <- unsafeRead a l
                           ....
    |
117 | sort4ByIndex cmp a i j k l = UNSAFE_CHECK(checkIndex) "sort4ByIndex" i (length a)
    |                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Data/Vector/Algorithms/Optimal.hs:117:91: error:
    • Couldn't match expected type ‘Int’ with actual type ‘Ck.Checks’
    • In the third argument of ‘Ck.checkIndex’, namely ‘Ck.Unsafe’
      In the first argument of ‘($)’, namely
        ‘((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 117)
            Ck.Unsafe)
           "sort4ByIndex" i (length a)’
      In the expression:
        ((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 117)
           Ck.Unsafe)
          "sort4ByIndex" i (length a)
          $ ((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 118)
               Ck.Unsafe)
              "sort4ByIndex" j (length a)
              $ ((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 119)
                   Ck.Unsafe)
                  "sort4ByIndex" k (length a)
                  $ ((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 120)
                       Ck.Unsafe)
                      "sort4ByIndex" l (length a)
                      $ do a0 <- unsafeRead a i
                           a1 <- unsafeRead a j
                           a2 <- unsafeRead a k
                           a3 <- unsafeRead a l
                           ....
    |
117 | sort4ByIndex cmp a i j k l = UNSAFE_CHECK(checkIndex) "sort4ByIndex" i (length a)
    |                                                                                           ^^^^^^^^^

src/Data/Vector/Algorithms/Optimal.hs:117:102: error:
    • Couldn't match type: [Char]
                     with: Int -> Int -> a0 -> m ()
      Expected: Int -> Int -> a0 -> m ()
        Actual: String
    • In the fourth argument of ‘Ck.checkIndex’, namely
        ‘"sort4ByIndex"’
      In the first argument of ‘($)’, namely
        ‘((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 117)
            Ck.Unsafe)
           "sort4ByIndex" i (length a)’
      In the expression:
        ((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 117)
           Ck.Unsafe)
          "sort4ByIndex" i (length a)
          $ ((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 118)
               Ck.Unsafe)
              "sort4ByIndex" j (length a)
              $ ((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 119)
                   Ck.Unsafe)
                  "sort4ByIndex" k (length a)
                  $ ((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 120)
                       Ck.Unsafe)
                      "sort4ByIndex" l (length a)
                      $ do a0 <- unsafeRead a i
                           a1 <- unsafeRead a j
                           a2 <- unsafeRead a k
                           a3 <- unsafeRead a l
                           ....
    • Relevant bindings include
        a :: v (PrimState m) e
          (bound at src/Data/Vector/Algorithms/Optimal.hs:117:18)
        sort4ByIndex :: Comparison e
                        -> v (PrimState m) e -> Int -> Int -> Int -> Int -> m ()
          (bound at src/Data/Vector/Algorithms/Optimal.hs:117:1)
    |
117 | sort4ByIndex cmp a i j k l = UNSAFE_CHECK(checkIndex) "sort4ByIndex" i (length a)
    |                                                                                                      ^^^^^^^^^^^^^^

src/Data/Vector/Algorithms/Optimal.hs:118:46: error:
    • Couldn't match type ‘[Char]’ with ‘Ck.Checks’
      Expected: Ck.Checks
        Actual: String
    • In the first argument of ‘Ck.checkIndex’, namely
        ‘"src/Data/Vector/Algorithms/Optimal.hs"’
      In the first argument of ‘($)’, namely
        ‘((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 118)
            Ck.Unsafe)
           "sort4ByIndex" j (length a)’
      In the second argument of ‘($)’, namely
        ‘((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 118)
            Ck.Unsafe)
           "sort4ByIndex" j (length a)
           $ ((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 119)
                Ck.Unsafe)
               "sort4ByIndex" k (length a)
               $ ((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 120)
                    Ck.Unsafe)
                   "sort4ByIndex" l (length a)
                   $ do a0 <- unsafeRead a i
                        a1 <- unsafeRead a j
                        a2 <- unsafeRead a k
                        a3 <- unsafeRead a l
                        ....’
    |
118 |                            $ UNSAFE_CHECK(checkIndex) "sort4ByIndex" j (length a)
    |                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Data/Vector/Algorithms/Optimal.hs:118:91: error:
    • Couldn't match expected type ‘Int’ with actual type ‘Ck.Checks’
    • In the third argument of ‘Ck.checkIndex’, namely ‘Ck.Unsafe’
      In the first argument of ‘($)’, namely
        ‘((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 118)
            Ck.Unsafe)
           "sort4ByIndex" j (length a)’
      In the second argument of ‘($)’, namely
        ‘((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 118)
            Ck.Unsafe)
           "sort4ByIndex" j (length a)
           $ ((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 119)
                Ck.Unsafe)
               "sort4ByIndex" k (length a)
               $ ((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 120)
                    Ck.Unsafe)
                   "sort4ByIndex" l (length a)
                   $ do a0 <- unsafeRead a i
                        a1 <- unsafeRead a j
                        a2 <- unsafeRead a k
                        a3 <- unsafeRead a l
                        ....’
    |
118 |                            $ UNSAFE_CHECK(checkIndex) "sort4ByIndex" j (length a)
    |                                                                                           ^^^^^^^^^

src/Data/Vector/Algorithms/Optimal.hs:118:102: error:
    • Couldn't match type: [Char]
                     with: Int -> Int -> a1 -> a0
      Expected: Int -> Int -> a1 -> a0
        Actual: String
    • In the fourth argument of ‘Ck.checkIndex’, namely
        ‘"sort4ByIndex"’
      In the first argument of ‘($)’, namely
        ‘((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 118)
            Ck.Unsafe)
           "sort4ByIndex" j (length a)’
      In the second argument of ‘($)’, namely
        ‘((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 118)
            Ck.Unsafe)
           "sort4ByIndex" j (length a)
           $ ((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 119)
                Ck.Unsafe)
               "sort4ByIndex" k (length a)
               $ ((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 120)
                    Ck.Unsafe)
                   "sort4ByIndex" l (length a)
                   $ do a0 <- unsafeRead a i
                        a1 <- unsafeRead a j
                        a2 <- unsafeRead a k
                        a3 <- unsafeRead a l
                        ....’
    |
118 |                            $ UNSAFE_CHECK(checkIndex) "sort4ByIndex" j (length a)
    |                                                                                                      ^^^^^^^^^^^^^^

src/Data/Vector/Algorithms/Optimal.hs:119:46: error:
    • Couldn't match type ‘[Char]’ with ‘Ck.Checks’
      Expected: Ck.Checks
        Actual: String
    • In the first argument of ‘Ck.checkIndex’, namely
        ‘"src/Data/Vector/Algorithms/Optimal.hs"’
      In the first argument of ‘($)’, namely
        ‘((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 119)
            Ck.Unsafe)
           "sort4ByIndex" k (length a)’
      In the second argument of ‘($)’, namely
        ‘((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 119)
            Ck.Unsafe)
           "sort4ByIndex" k (length a)
           $ ((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 120)
                Ck.Unsafe)
               "sort4ByIndex" l (length a)
               $ do a0 <- unsafeRead a i
                    a1 <- unsafeRead a j
                    a2 <- unsafeRead a k
                    a3 <- unsafeRead a l
                    ....’
    |
119 |                            $ UNSAFE_CHECK(checkIndex) "sort4ByIndex" k (length a)
    |                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Data/Vector/Algorithms/Optimal.hs:119:91: error:
    • Couldn't match expected type ‘Int’ with actual type ‘Ck.Checks’
    • In the third argument of ‘Ck.checkIndex’, namely ‘Ck.Unsafe’
      In the first argument of ‘($)’, namely
        ‘((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 119)
            Ck.Unsafe)
           "sort4ByIndex" k (length a)’
      In the second argument of ‘($)’, namely
        ‘((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 119)
            Ck.Unsafe)
           "sort4ByIndex" k (length a)
           $ ((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 120)
                Ck.Unsafe)
               "sort4ByIndex" l (length a)
               $ do a0 <- unsafeRead a i
                    a1 <- unsafeRead a j
                    a2 <- unsafeRead a k
                    a3 <- unsafeRead a l
                    ....’
    |
119 |                            $ UNSAFE_CHECK(checkIndex) "sort4ByIndex" k (length a)
    |                                                                                           ^^^^^^^^^

src/Data/Vector/Algorithms/Optimal.hs:119:102: error:
    • Couldn't match type: [Char]
                     with: Int -> Int -> a2 -> a1
      Expected: Int -> Int -> a2 -> a1
        Actual: String
    • In the fourth argument of ‘Ck.checkIndex’, namely
        ‘"sort4ByIndex"’
      In the first argument of ‘($)’, namely
        ‘((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 119)
            Ck.Unsafe)
           "sort4ByIndex" k (length a)’
      In the second argument of ‘($)’, namely
        ‘((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 119)
            Ck.Unsafe)
           "sort4ByIndex" k (length a)
           $ ((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 120)
                Ck.Unsafe)
               "sort4ByIndex" l (length a)
               $ do a0 <- unsafeRead a i
                    a1 <- unsafeRead a j
                    a2 <- unsafeRead a k
                    a3 <- unsafeRead a l
                    ....’
    |
119 |                            $ UNSAFE_CHECK(checkIndex) "sort4ByIndex" k (length a)
    |                                                                                                      ^^^^^^^^^^^^^^

src/Data/Vector/Algorithms/Optimal.hs:120:46: error:
    • Couldn't match type ‘[Char]’ with ‘Ck.Checks’
      Expected: Ck.Checks
        Actual: String
    • In the first argument of ‘Ck.checkIndex’, namely
        ‘"src/Data/Vector/Algorithms/Optimal.hs"’
      In the first argument of ‘($)’, namely
        ‘((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 120)
            Ck.Unsafe)
           "sort4ByIndex" l (length a)’
      In the second argument of ‘($)’, namely
        ‘((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 120)
            Ck.Unsafe)
           "sort4ByIndex" l (length a)
           $ do a0 <- unsafeRead a i
                a1 <- unsafeRead a j
                a2 <- unsafeRead a k
                a3 <- unsafeRead a l
                ....’
    |
120 |                            $ UNSAFE_CHECK(checkIndex) "sort4ByIndex" l (length a) $ do
    |                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Data/Vector/Algorithms/Optimal.hs:120:91: error:
    • Couldn't match expected type ‘Int’ with actual type ‘Ck.Checks’
    • In the third argument of ‘Ck.checkIndex’, namely ‘Ck.Unsafe’
      In the first argument of ‘($)’, namely
        ‘((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 120)
            Ck.Unsafe)
           "sort4ByIndex" l (length a)’
      In the second argument of ‘($)’, namely
        ‘((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 120)
            Ck.Unsafe)
           "sort4ByIndex" l (length a)
           $ do a0 <- unsafeRead a i
                a1 <- unsafeRead a j
                a2 <- unsafeRead a k
                a3 <- unsafeRead a l
                ....’
    |
120 |                            $ UNSAFE_CHECK(checkIndex) "sort4ByIndex" l (length a) $ do
    |                                                                                           ^^^^^^^^^

src/Data/Vector/Algorithms/Optimal.hs:120:102: error:
    • Couldn't match type: [Char]
                     with: Int -> Int -> m0 () -> a2
      Expected: Int -> Int -> m0 () -> a2
        Actual: String
    • In the fourth argument of ‘Ck.checkIndex’, namely
        ‘"sort4ByIndex"’
      In the first argument of ‘($)’, namely
        ‘((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 120)
            Ck.Unsafe)
           "sort4ByIndex" l (length a)’
      In the second argument of ‘($)’, namely
        ‘((Ck.checkIndex "src/Data/Vector/Algorithms/Optimal.hs" 120)
            Ck.Unsafe)
           "sort4ByIndex" l (length a)
           $ do a0 <- unsafeRead a i
                a1 <- unsafeRead a j
                a2 <- unsafeRead a k
                a3 <- unsafeRead a l
                ....’
    |
120 |                            $ UNSAFE_CHECK(checkIndex) "sort4ByIndex" l (length a) $ do
    |                                                                                                      ^^^^^^^^^^^^^^
[ 8 of 11] Compiling Data.Vector.Algorithms.Radix ( src/Data/Vector/Algorithms/Radix.hs, /home/matt/Projects/vector-algorithms/dist-newstyle/build/x86_64-linux/ghc-9.4.0.20220501/vector-algorithms-0.8.0.4/build/D
ata/Vector/Algorithms/Radix.o, /home/matt/Projects/vector-algorithms/dist-newstyle/build/x86_64-linux/ghc-9.4.0.20220501/vector-algorithms-0.8.0.4/build/Data/Vector/Algorithms/Radix.dyn_o )
[ 9 of 11] Compiling Data.Vector.Algorithms.Search ( src/Data/Vector/Algorithms/Search.hs, /home/matt/Projects/vector-algorithms/dist-newstyle/build/x86_64-linux/ghc-9.4.0.20220501/vector-algorithms-0.8.0.4/build
/Data/Vector/Algorithms/Search.o, /home/matt/Projects/vector-algorithms/dist-newstyle/build/x86_64-linux/ghc-9.4.0.20220501/vector-algorithms-0.8.0.4/build/Data/Vector/Algorithms/Search.dyn_o )
cabal: Failed to build vector-algorithms-0.8.0.4 (which is required by
test:properties from vector-algorithms-0.8.0.4).
```

I fixed a similar issue in `bitvec`, so I may be able to do that here. But there's *more* CPP that we're doing in this package... https://github.com/Bodigrim/bitvec/pull/57/files#diff-68badb82a0c9ab25a78e63d1647241a69cf4110c3050cd02158b997cb81006f6L441

### CODE REVIEW

**Comment by parsonsmatt** [comment]
Alright, tests pass locally on GHC 9.4 with the PR in current state.

Problem: depends on as-of-yet unreleased `vector`.

May be able to CPP this to support latest Hackage as well as the new interface, but it seems dicey. Thoughts?

**Comment by erikd** [comment]
This package has had support for an incredibly wide range of GHC versions. We would like to keep that as much as possible.

**Comment by juhp** [comment]
vector-0.13 has been released

**Comment by erikd** [comment]
I think version `0.9.0.1` on Hackage should now support this.

**Pull request closed without merging**
