### PR TITLE
Add sortUniq and nub functions

### PR DESCRIPTION
**Pull request by Boarders**
Add a `sortUniq` function to each sort variant which first sorts the vector and then does a pass to remove all duplicates.

### CODE REVIEW

**Comment by Boarders** [comment]
I should say that I wanted to add this function so I can implement `nub` on top of it.

**Comment by Boarders** [comment]
I was hoping to add some more non-sort based functions built on top of the modules introduced in this PR, could you let me know when you might be able to have a look at it @erikd? Thank you!

**Comment by Boarders** [comment]
ping @erikd

**Comment by erikd** [comment]
Thanks!

**Comment by erikd** [comment]
@Boarders Should I release this as is or is there more coming?

**Comment by Boarders** [comment]
I was going to add some shuffle functions in the new module, what do you think?

**Comment by erikd** [comment]
Sure, a release can wait for that.

**Pull request merged**
